import type { Metadata } from 'next';
import './globals.css';
import Provider from '@/utils/provider';

export const metadata: Metadata = {
  title: 'Taskflow - Project Management Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='h-full'>
      <body className='h-full flex flex-col'>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
