# Generated by Django 4.2.6 on 2024-01-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_task_completed_task_status_task_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
